ruyi-repo = "v1"

[repo]
doc_uri = "https://ruyisdk.org/docs/intro"
id = "ruyisdk"

[[telemetry]]
id = "ruyisdk-hq-pm"
scope = "pm"
url = "https://api.ruyisdk.cn/telemetry/pm/"

[[mirrors]]
id = "ruyi-dist"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/dist/",
]

[[mirrors]]
id = "ruyi-3rdparty-canaan"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/canaan/",
]

[[mirrors]]
id = "ruyi-3rdparty-milkv"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/milkv/",
]

# Mirrors of third-party software

[[mirrors]]
id = "freebsd-releases"
urls = [
  "https://mirror.iscas.ac.cn/FreeBSD/releases",
  "https://download.freebsd.org/releases",
  "https://archive.freebsd.org/old-releases",
]

[[mirrors]]
id = "freebsd-old-releases"
urls = [
  "https://archive.freebsd.org/old-releases",
]

[[mirrors]]
id = "openbsd"
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/OpenBSD",
  "https://cdn.openbsd.org/pub/OpenBSD",
  "https://ftp.openbsd.org/pub/OpenBSD",
]

[[mirrors]]
id = "revyos"
urls = [
  "https://mirror.iscas.ac.cn/revyos",
]

[[mirrors]]
id = "ubuntu-cdimage"
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cdimage",
  "https://cdimage.ubuntu.com",
]
