format = "v1"

[metadata]
desc = "The LLVM compiler infrastructure (upstream)"
vendor = { name = "llvm-project", eula = "" }

[[distfiles]]
name = "llvm-project-21.1.0.src.tar.xz"
size = 158971856
urls = [
  "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/llvm-project-21.1.0.src.tar.xz",
]

[distfiles.checksums]
sha256 = "1672e3efb4c2affd62dbbe12ea898b28a451416c7d95c1bd0190c26cbe878825"
sha512 = "1487dcdc041dd6cdcffa6cc95a565e18a9fce2a73215671e366a9601cecce6c8bf70065df5564de5998d1841c3d8d829a9fbd2cad72e3aab4db279e8885ff446"

[source]
distfiles = ["llvm-project-21.1.0.src.tar.xz"]
