format = "v1"

[metadata]
desc = "Debian image for Sipeed LicheeRV Nano with Sophgo SG200x, from https://github.com/Fishwaldo"
vendor = { name = "github:Fishwaldo", eula = "" }
upstream_version = "v1.2.0"

[[distfiles]]
name = "licheervnano_sd.img.lz4"
size = 193101308
urls = [
  "https://github.com/Fishwaldo/sophgo-sg200x-debian/releases/download/v1.2.0/licheervnano_sd.img.lz4",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3d4e44cc2b5240f76e29ee48a096a3bb550a57772d22b3c0bc32fd798722e2be"
sha512 = "28740a981db4a846892f6bccde2c2b6444e7919199bb99809ca5053448f558e422f12d294e0420e22d35d88c8e013123861a013d5fd6aeb36e4c4bed65330403"

[blob]
distfiles = [
  "licheervnano_sd.img.lz4",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "licheervnano_sd.img"
