format = "v1"

[metadata]
desc = "Debian image for Sipeed LicheeRV Nano with Sophgo SG200x, from https://github.com/Fishwaldo"
vendor = { name = "github:Fishwaldo", eula = "" }
upstream_version = "v1.3.0"

[[distfiles]]
name = "licheervnano_sd.img.lz4"
size = 200841302
urls = [
  "https://github.com/Fishwaldo/sophgo-sg200x-debian/releases/download/v1.3.0/licheervnano_sd.img.lz4",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "d37d3ca0153e908d162c31641e936405cebc6b9dcacfa6c135d77d9d1b0be644"
sha512 = "92daec4098ab46e3e7ab599c5547835d37845a0d870a2d0cd4ff70859c683468484cb89bee3dd486ba8d6aa582ea5c7ba01153ea1f11d18855c16be01f6cc69d"

[blob]
distfiles = [
  "licheervnano_sd.img.lz4",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "licheervnano_sd.img"
