format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 8G RAM), for RevyOS, v1.0.0"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v1.0.0"

[[distfiles]]
name = "u-boot-with-spl-milkv-meles-dualrank-1.0.0.bin"
unpack = "raw"
size = 751552
urls = [
  "https://github.com/milkv-meles/meles-images/releases/download/v1.0.0/u-boot-with-spl-dualrank.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b529d8c8c54f7748170d9c1c4945f0460e3f5efac7ffd53e2bc36a379a1649ec"
sha512 = "49ecd1e6d000919567be745dedbe154b3f26811b9ef0d98d883d726e18a70d6259b865699a61be5434fc9a3c88c021ed4776afe03af52d2166870ba0befb38ca"

[blob]
distfiles = [
  "u-boot-with-spl-milkv-meles-dualrank-1.0.0.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-milkv-meles-dualrank-1.0.0.bin"
