format = "v1"

[[distfiles]]
name = "u-boot-with-spl-meles-20240720.bin"
size = 780464
urls = ["https://mirror.iscas.ac.cn/revyos/extra/images/meles/20240720/u-boot-with-spl-meles.bin", ]
restrict = ["mirror", ]

[distfiles.checksums]
sha256 = "75e026f1e80cb435ff3e4aa871c2d06d857267cb75a46c0118eda30558cc304d"
sha512 = "625f9af0909fe5cfb05fb1441a609797eb8fcf2639379ab0895afd66d80f651f47ca4c28332538422d50697351c12d3a9275d5abef9221968c15f601ee261532"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 8G RAM), for RevyOS, 20240720"
upstream_version = "20240720"

[blob]
distfiles = ["u-boot-with-spl-meles-20240720.bin", ]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[metadata.vendor]
name = "Milk-V"
eula = ""

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-20240720.bin"

