format = "v1"

[[distfiles]]
name = "u-boot-with-spl-meles-20240601.bin"
size = 780192
urls = ["https://mirror.iscas.ac.cn/revyos/extra/images/meles/20240601/u-boot-with-spl-meles.bin", ]
restrict = ["mirror", ]

[distfiles.checksums]
sha256 = "d7b629be90d4a39d5d8b5a5c6f8d70b130125fa409bc02544fd476b793555580"
sha512 = "abaaa1ce7118093d67fd6272fcc5745a5b1c474a2a20d98d5d055702d02a99ca5c1eb0959f36c4957cc5a6a94c203f93dbb18c0fe394ce29197bc4a27d5bfe15"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 8G RAM), for RevyOS, 20240601"
upstream_version = "20240601"

[blob]
distfiles = ["u-boot-with-spl-meles-20240601.bin", ]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[metadata.vendor]
name = "Milk-V"
eula = ""

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-20240601.bin"

