ruyi-entity = "v0"

related = ["arch:riscv32"]
unique_among_type_during_traversal = true

# source: https://www.wch.cn/products/QingKe.html?categoryId=77
# retrieved 2025-05-25
[uarch]
id = "wch-qingke-v5a"
display_name = "WCH Qingke V5A"
arch = "riscv32"

[uarch.riscv]
isa = "rv32imafcb"
