ruyi-entity = "v0"

related = ["arch:riscv64"]
unique_among_type_during_traversal = true

[uarch]
id = "xiangshan-kunminghu"
display_name = "Xiangshan Kunminghu"
arch = "riscv64"

[uarch.riscv]
isa = "rv64imafdcbvh_sdtrig_sha_shcounterenw_shgatpa_shlcofideleg_shtvala_shvsatpa_shvstvala_shvstvecd_smaia_smcsrind_smdbltrp_smmpm_smnpm_smrnmi_smstateen_ssaia_ssccptr_sscofpmf_sscounterenw_sscsrind_ssdbltrp_ssnpm_sspm_ssstateen_ssstrict_sstc_sstvala_sstvecd_ssu64xl_supm_svade_svbare_svinval_svnapot_svpbmt_za64rs_zacas_zawrs_zba_zbb_zbc_zbkb_zbkc_zbkx_zbs_zcb_zcmop_zfa_zfh_zfhmin_zic64b_zicbom_zicbop_zicboz_ziccif_zicclsm_ziccrse_zicntr_zicond_zicsr_zifencei_zihintpause_zihpm_zimop_zkn_zknd_zkne_zknh_zksed_zksh_zkt_zvbb_zvfh_zvfhmin_zvkt_zvl128b_zvl32b_zvl64b"
