ruyi-entity = "v0"

related = ["arch:riscv64"]
unique_among_type_during_traversal = true

[uarch]
id = "xuantie-c908v"
display_name = "Xuantie C908V"
arch = "riscv64"

[uarch.riscv]
isa = "rv64imafdcv_zicbom_zicbop_zicboz_zicntr_zicsr_zifencei_zihintpause_zihpm_zfh_zba_zbb_zbc_zbs_zvfh_sstc_svinval_svnapot_svpbmt_xtheadba_xtheadbb_xtheadbs_xtheadcmo_xtheadcondmov_xtheadfmemidx_xtheadmac_xtheadmemidx_xtheadmempair_xtheadsync_xtheadvdot"
