format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Single-rank, 4G RAM), for RevyOS, v1.0.0"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v1.0.0"

[[distfiles]]
name = "u-boot-with-spl-milkv-meles-singlerank-1.0.0.bin"
unpack = "raw"
size = 751568
urls = [
  "https://github.com/milkv-meles/meles-images/releases/download/v1.0.0/u-boot-with-spl-singlerank.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "500b261a3dca0e64cd78c95e4952bfea20fccc081754872339d6a3bf6accf41f"
sha512 = "6004b30a452e8cf230e48cb7d9397e11f5d421d9960e6a08bae5ecafb8c34ca11f52c4bdc8c474c7d6cd06bc760008d1d799ce6439fbbe53421e4c8a0a805bec"

[blob]
distfiles = [
  "u-boot-with-spl-milkv-meles-singlerank-1.0.0.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-milkv-meles-singlerank-1.0.0.bin"
