format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Single-rank, 4G RAM), for RevyOS, 20241229"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "20241229"

[[distfiles]]
name = "u-boot-with-spl-meles-4g-20241229.bin"
size = 782024
urls = [
  "mirror://revyos/extra/images/meles/20241229/u-boot-with-spl-meles-4g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "cf2e49d6ac2ecd402d0acca8011d60ec7f6705313dc64086d6486ed6b6613d7d"
sha512 = "78518e4058506259f401b84370dfc69a537a72e703e45e8446d7acf32bb78145ff94afd6aa9801dbd7b2120c17998a9c3592d29f551f2372f5864ef328077ae0"

[blob]
distfiles = [
  "u-boot-with-spl-meles-4g-20241229.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-4g-20241229.bin"
