format = "v1"

[[distfiles]]
name = "u-boot-with-spl-meles-4g-20240720.bin"
size = 780464
urls = ["https://mirror.iscas.ac.cn/revyos/extra/images/meles/20240720/u-boot-with-spl-meles-4g.bin", ]
restrict = ["mirror", ]

[distfiles.checksums]
sha256 = "3fcd346ef849b7fba17fb34a39ed7a96c597de6cb4f4aa8b1778339ffbba0280"
sha512 = "6e3c3ae5396cf43a845e4f8c5f4a71c2ff7f50914cb6fd2a6137a0404970d61cf6be92dec7ff6883c7b40354642a2e20b5fb3080b648446c7042b85a572bbe89"

[metadata]
desc = "U-Boot image for Milk-V Meles (Single-rank, 4G RAM), for RevyOS, 20240720"
upstream_version = "20240720"

[blob]
distfiles = ["u-boot-with-spl-meles-4g-20240720.bin", ]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[metadata.vendor]
name = "Milk-V"
eula = ""

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-4g-20240720.bin"

