format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Linux GNU Toolchain 20250526 (Xuantie 3.1.0 sources, built by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-HOST-aarch64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"
size = 328726736

[distfiles.checksums]
sha256 = "039fafaeae30ae6d57c78d1280922ddcbee3712d61cac63c94be91f53a4f85c9"
sha512 = "807e822d13df463bba378ff2a231a8d61adc40dc9cdc3f2e0baf1233821b2d615ccd393cb2d38658b9d8d564451e69252e0903042705b2a1bd0dd2c06074e158"

[[distfiles]]
name = "RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-HOST-riscv64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"
size = 333942804

[distfiles.checksums]
sha256 = "12b7e6de8798324452ca307c1d0dc03907ce2bcb838f8e7bba1ef989ea32bbba"
sha512 = "c070fc5bad392e0e5f009ee2aa33149fc8c33affade3a7313df48a81a8dd4b4b82a18afdf17ea830afb5b025f66f8475d7827fc7b705f0585255a0909cfb9ce7"

[[distfiles]]
name = "RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-riscv64-plctxthead-linux-gnu.tar.xz"
size = 341282440

[distfiles.checksums]
sha256 = "52f7c2673cefeeb8632eb16144b9cedfb413f7eab037a12e1a8cee1f043f166a"
sha512 = "174c48d284c5bff3c26ab3a114e0ebd59e338d4c09a5cb3f73b06b93eeac6e606e8e0fbd56649019ca946ed4240ef03ed98afd05f5ea68a35f253a00039a03a4"

[[binary]]
host = "aarch64"
distfiles = ["RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-HOST-aarch64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"]

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-HOST-riscv64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20250526-Xuantie-Sources-Xuantie-3.1.0-riscv64-plctxthead-linux-gnu.tar.xz"]

[toolchain]
target = "riscv64-plctxthead-linux-gnu"
flavors = ["xthead"]
components = [
  { name = "binutils", version = "2.42" },
  { name = "gcc", version = "14.1.1" },
  { name = "gdb", version = "10.0" },
  { name = "glibc", version = "2.33" },
  { name = "linux-headers", version = "6.14" },
]
included_sysroot = "riscv64-plctxthead-linux-gnu/sysroot"
