format = "v1"

[metadata]
desc = "Official FreeBSD 14.2 RELEASE riscv64 live image"
vendor = { name = "FreeBSD", eula = "" }
upstream_version = "14.2"

[[distfiles]]
name = "FreeBSD-14.2-RELEASE-riscv-riscv64-mini-memstick.img"
size = 525514240
urls = [
  "mirror://freebsd-releases/riscv/riscv64/ISO-IMAGES/14.2/FreeBSD-14.2-RELEASE-riscv-riscv64-mini-memstick.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "227f6f857db96542541bdcfc756a8b4a9fcf7d9fa37badd4c5a5f23581a4d1ca"
sha512 = "ef3eeba7518643b74ec9c611fb632826c943925817120ad85f63db29776769093e6daf44d7d2316e80b8ffae2623e6b68209c3de43e0e5ec185acabc16c980ef"

[blob]
distfiles = [
  "FreeBSD-14.2-RELEASE-riscv-riscv64-mini-memstick.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
live = "FreeBSD-14.2-RELEASE-riscv-riscv64-mini-memstick.img"
