format = "v1"

[metadata]
desc = "Official FreeBSD 14.3 RELEASE riscv64 live image"
vendor = { name = "FreeBSD", eula = "" }
upstream_version = "14.3"

[[distfiles]]
name = "FreeBSD-14.3-RELEASE-riscv-riscv64-mini-memstick.img"
size = 490255872
urls = [
  "mirror://freebsd-releases/riscv/riscv64/ISO-IMAGES/14.3/FreeBSD-14.3-RELEASE-riscv-riscv64-mini-memstick.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "075a52b1eb03299decbf51fe78392c1c13b3046759aa2980fa09d34628505d85"
sha512 = "14c67f8ebd224b59b22c17020826549f637172bbb704b245cabe6fc34f3fdbe72ad577ba8a1f4344fda107aa0f10e48f5a5fbfbf74aa24302f9679a48cc15826"

[blob]
distfiles = [
  "FreeBSD-14.3-RELEASE-riscv-riscv64-mini-memstick.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
live = "FreeBSD-14.3-RELEASE-riscv-riscv64-mini-memstick.img"
