format = "v1"

[metadata]
desc = "Official Milk-V Duo GNU Toolchain (bare-metal, prebuilt by Milk-V)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "gnu-milkv-milkv-duo-elf-bin.67688c7335e7.tar.zst"
size = 86068322
urls = [
  "mirror://ruyi-3rdparty-milkv/repacks/gnu-milkv-milkv-duo-elf-bin.67688c7335e7.tar.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "851694a3b2a5250972db4d6a029f783c44c13a25435ead6a0aa5394348366d14"
sha512 = "fd0d6803c6ae87bd76d57e7d813d7c00c21e796689cba4eead9575b2a2082b92bd3c70536085beb1fac38202a956e5b22ed7bd4076b82b1ff1b171c4e2548235"

[[binary]]
host = "x86_64"
distfiles = ["gnu-milkv-milkv-duo-elf-bin.67688c7335e7.tar.zst"]

[toolchain]
target = "riscv64-unknown-elf"
flavors = ["xthead"]
components = [
  { name = "binutils", version = "2.32" },
  { name = "gcc", version = "10.2.0" },
  { name = "gdb", version = "8.2" },
]
