format = "v1"

[metadata]
desc = "CanMV Linux SDK image for Canaan Kendryte K230D, built by PLCT, RV64LP64 ABI, with demos"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "kendryte-k230d-linux-sdk-demo.rv64lp64.20240731.ext4.img.zst"
size = 41634434
urls = [
  "mirror://ruyi-3rdparty-canaan/temp/kendryte-k230d-linux-sdk-demo.rv64lp64.20240731.ext4.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "e4794957663e331a3cbdee5bfc474da5e10094f640ba89ebd8570c584a0ca1ff"
sha512 = "0d51b0559bc219603303945ec42b431f98b57ef378cef9bd9e1cec2113bbd972601fc20ad5fce3ec15b4a5d4868e58231c83a3c9959c8a989ddf3c01e143cf08"

[blob]
distfiles = [
  "kendryte-k230d-linux-sdk-demo.rv64lp64.20240731.ext4.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "kendryte-k230d-linux-sdk-demo.rv64lp64.20240731.ext4.img"
