format = "v1"

[metadata]
desc = "U-Boot image for LicheePi 4A (8G RAM) and RevyOS 20231210"
vendor = { name = "PLCT", eula = "" }
upstream_version = "20231210"

[[distfiles]]
name = "u-boot-with-spl-lpi4a-8g.20231210.bin"
size = 963368
urls = [
  "mirror://revyos/extra/images/lpi4a/20231210/u-boot-with-spl-lpi4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bcaf013e0fc31e5eeed39036d1989bea4984a65730fd2b3b271e88a2eb2c2763"
sha512 = "46d97035d793fc7f18c8e3dbd7b7cd5a99b2b3f3ea99d9e696572fd368b8c7e65032ae71745bf13a132e349fbda10343dd7a3bf7cd44768d13c22d55ab7b4710"

[blob]
distfiles = [
  "u-boot-with-spl-lpi4a-8g.20231210.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lpi4a-8g.20231210.bin"
