format = "v1"

[metadata]
desc = "CanMV Linux SDK image for Canaan Kendryte K230D, built by PLCT, RV64ILP32 ABI, with demos"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240731.ext4.img.zst"
size = 30493849
urls = [
  "mirror://ruyi-3rdparty-canaan/temp/kendryte-k230d-linux-sdk-demo.rv64ilp32.20240731.ext4.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "3e1432d2f951c177f8688a6f0c28896e2143661d6fbdab1da09afc7afa852ef7"
sha512 = "3c24b26ab58d18c3bb42d635dbf3679af113f3a260185c3fd7b29b9a52b0b449be7a8f9655ba9a279e9ca0f892959f9e6f6f0fd20feabea632df1b5eb7fc88c9"

[blob]
distfiles = [
  "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240731.ext4.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "kendryte-k230d-linux-sdk-demo.rv64ilp32.20240731.ext4.img"
