format = "v1"

[metadata]
desc = "Official Milk-V Duo GNU Toolchain (musl libc, prebuilt by Milk-V)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "gnu-milkv-milkv-duo-musl-bin.67688c7335e7.tar.zst"
size = 113853159
urls = [
  "mirror://ruyi-3rdparty-milkv/repacks/gnu-milkv-milkv-duo-musl-bin.67688c7335e7.tar.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "267f963b9664d0777dab15e8ed3b257ec91a1e5940e7f80f4f3fec2e46bd113d"
sha512 = "631082e733f6adc3bfb773cd967815acff76954ee76f2e79224115c73e5bd10aada56087720e973a18d4111e711b900bda4ba88c200d8c9e7f85a3a292f32d73"

[[binary]]
host = "x86_64"
distfiles = ["gnu-milkv-milkv-duo-musl-bin.67688c7335e7.tar.zst"]

[toolchain]
target = "riscv64-unknown-linux-musl"
flavors = ["xthead"]
components = [
  { name = "binutils", version = "2.35" },
  { name = "gcc", version = "10.2.0" },
  { name = "gdb", version = "10.0" },
  { name = "linux-headers", version = "5.10" },
  { name = "musl", version = "1.2.2" },
]
included_sysroot = "sysroot"
