format = "v1"

[metadata]
desc = "U-Boot image for Sipeed Lichee Console 4A (16G RAM) and RevyOS 20240720"
vendor = { name = "Sipeed", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "u-boot-with-spl-lcon4a-16g.bin"
size = 1032040
urls = [
  "mirror://revyos/extra/images/lcon4a/20240720/u-boot-with-spl-lcon4a-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "789174663c219955c94e87b0b9351ae74c71cb9ebd4efafe008fd4f3c064f533"
sha512 = "1292b8bfc71cc381512c6330f0f549c7b87702650c1513c959584a72c3591244f2bd87bc051a5a5038b1dabf1271327c774eddbf928c576430935c66941c2634"

[blob]
distfiles = [
  "u-boot-with-spl-lcon4a-16g.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lcon4a-16g.bin"
