format = "v1"

[metadata]
desc = "U-Boot image for Sipeed Lichee Console 4A (8G RAM) and RevyOS 20250729"
vendor = { name = "Sipeed", eula = "" }
upstream_version = "20250729"

[[distfiles]]
name = "u-boot-with-spl-lcon4a.bin"
size = 1032072
urls = [
  "mirror://revyos/extra/images/lcon4a/20250729/u-boot-with-spl-lcon4a.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "6e314da77137b336f49f7bee4970765ba6f648cef9f93e51eb0756f0142ef39f"
sha512 = "f794e32760d15dda505e9725bd6fe9a01ae85cb5aaad13362baaa90465eee5dbb96535d574a30775fb0ff929755f07335b95e0878cb652c5edb0dd7f1ad9da42"

[blob]
distfiles = [
  "u-boot-with-spl-lcon4a.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-lcon4a.bin"
