format = "v1"

[metadata]
desc = "U-Boot image for Milk-V Meles (Dual-rank, 16G RAM), for RevyOS, 20240720"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "20240720"

[[distfiles]]
name = "u-boot-with-spl-meles-16g-20240720.bin"
size = 780464
urls = [
  "https://mirror.iscas.ac.cn/revyos/extra/images/meles/20240720/u-boot-with-spl-meles-16g.bin",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f79d2278b8d37d4ffae9d4f54f6e95e97f94d7125e5fa330c4c2f2067d5e6cc8"
sha512 = "ed0f8785ea18ff292b9d8744b39503b9b4ce2a68fee8708a7814efa36c36cd67a0a89a5e559a76b4bba47dd16cf2690c21aaac480c9c9dc84fbab466f397126a"

[blob]
distfiles = [
  "u-boot-with-spl-meles-16g-20240720.bin",
]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[provisionable.partition_map]
uboot = "u-boot-with-spl-meles-16g-20240720.bin"
