format = "v1"

[metadata]
desc = "Official Milk-V Duo GNU Toolchain (GNU libc, prebuilt by Milk-V)"
vendor = { name = "Milk-V", eula = "" }

[[distfiles]]
name = "gnu-milkv-milkv-duo-bin.67688c7335e7.tar.zst"
size = 309989522
urls = [
  "mirror://ruyi-3rdparty-milkv/repacks/gnu-milkv-milkv-duo-bin.67688c7335e7.tar.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b088dab24342c8299dbae051ebedbe4dd44a2c19f54b14468ddbe811e3ce8351"
sha512 = "9c170f9b4cd8fa013f236ee75b94675a9214142cd275805202472b19bbe80272cd9a9862ecf21faec2ad1d0d57ead4a79bcb739e44149653870abad1f3242726"

[[binary]]
host = "x86_64"
distfiles = ["gnu-milkv-milkv-duo-bin.67688c7335e7.tar.zst"]

[toolchain]
target = "riscv64-unknown-linux-gnu"
flavors = ["xthead"]
components = [
  { name = "binutils", version = "2.35" },
  { name = "gcc", version = "10.2.0" },
  { name = "gdb", version = "10.0" },
  { name = "glibc", version = "2.33" },
  { name = "linux-headers", version = "5.10" },
]
included_sysroot = "sysroot"
