format = "v1"

[metadata]
desc = "Open Source Computer Vision Library (upstream)"
vendor = { name = "opencv", eula = "" }

[[distfiles]]
name = "opencv-4.12.0.tar.gz"
size = 95254890
urls = [
  "https://github.com/opencv/opencv/archive/refs/tags/4.12.0.tar.gz",
]

[distfiles.checksums]
sha256 = "44c106d5bb47efec04e531fd93008b3fcd1d27138985c5baf4eafac0e1ec9e9d"
sha512 = "8ac63ddd61e22cc0eaeafee4f30ae6e1cab05fc4929e2cea29070203b9ca8dfead12cc0fd7c4a87b65c1e20ec6b9ab4865a1b83fad33d114fc0708fdf107c51b"

[source]
distfiles = ["opencv-4.12.0.tar.gz"]
